envVars:
  - key: DB_HOST
    value: "aiven-2a96aec-davidsaavedrapinzon13-4cbb.f.aivencloud.com"
  - key: DB_PORT
    value: "24518"
  - key: DB_NAME
    value: "defaultdb"
  - key: DB_USER
    value: "avnadmin"
  - key: DB_PASS
    value: "tu_contraseña_de_aiven"